[package]
version.workspace = true
edition.workspace = true
publish.workspace = true
name = "binaryen-sys"
links = "binaryen"

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2"
cmake = "0.1"
flate2 = "1"
tar = "0.4"
ureq = "3"
