[workspace]
members = ["binaryen-sys"]

[workspace.package]
version = "0.123.0"
edition = "2024"
publish = false

[package]
version.workspace = true
edition.workspace = true
publish.workspace = true
name = "binaryen"

[dependencies]
binaryen-sys = { path = "binaryen-sys" }
libc = "0.2"
